name: Create new release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version for the new release (if not given it will get it from 'mod.txt')"
        required: false
        type: string


env:
    VERSION: ${{ github.event.inputs.version }}


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Archive Mod
      run: |
         zip -r "./GoatHighlighter.zip" "./Goat Highlighter/"
    - name: Calculate Hash
      id: hash
      run: |
        HASH=$(find "./Goat Highlighter/" -type f -exec sha256sum -b {} \; | sort -f -k2 | awk '{print $1}' | tr -d '\n' | sha256sum -b | awk '{print $1}') # This calculates the hash for every file, joins them in a single string and then calculates the hash of that
        echo "HASH=${HASH}" >> $GITHUB_ENV
    - name: Create mod meta file
      id: create_meta_file
      run: |
        cat <<EOM > ./meta.json
        [
            {
                "ident" : "goat-highlighter",
                "hash" : "${HASH}",
                "patchnotes_url" : "https://github.com/$GITHUB_REPOSITORY/releases/latest",
                "download_url" : "https://github.com/$GITHUB_REPOSITORY/releases/latest/download/GoatHighlighter.zip"
            }
        ]
        EOM
    - name: Get Mod Version
      if: "${{ env.VERSION == '' }}"
      run: |
         VERSION=$(cat "Goat Highlighter/mod.txt" | grep -E '^[ \t]*"version": "([^"]+)",[ \t]*' | grep -oE '[0-9.]+')
         echo "Found version: ${VERSION}"
         echo "VERSION=${VERSION}" >> $GITHUB_ENV
    - name: Create New Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./GoatHighlighter.zip
          ./meta.json
          ./.github/Changelog.md
        fail_on_unmatched_files: true
        name: Version ${{ env.VERSION }}
        tag_name: v${{ env.VERSION }}
        draft: false
        prerelease: false
        body_path: ./.github/Changelog.md